### ISSUE TITLE
Deploy-to-Heroku not fully configured

### ISSUE THREAD

**Issue by skye2k2** [Talkdesk/pr-police#7]
Love this, BTW. However, using the automated deploy-to-Heroku button results in an application error:

```
[timestamp] heroku[web.1]: Process exited with status 137
[timestamp] heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
[timestamp] heroku[web.1]: Stopping process with SIGKILL
[timestamp] heroku[web.1]: Process exited with status 137
```

For some reason, the app seems to be trying to start a web instead of a worker process. Using the same configuration locally from a clone of the repository works just fine. Downloading the resulting Heroku slug (`heroku slugs:download -a APP_NAME`) also works locally. 😕

**Comment by rogeriopvl** [comment]
Thanks for reporting this @skye2k2 , I'm going to investigate this further.
